[build]
  publish = "build/web"
  
[build.environment]
  # Usa buildpack Flutter
  FLUTTER_VERSION = "3.19.0"
  FLUTTER_CHANNEL = "stable"

# Build hook per installare Flutter tramite buildpack
[build.processing]
  skip_processing = false

[[plugins]]
  package = "netlify-plugin-flutter-web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"