name: ai_assistant_mvp
description: "AI Integration Platform for Business - MVP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^13.2.5
  
  # Backend Supabase
  supabase_flutter: ^2.3.4
  
  # Network & APIs
  dio: ^5.4.0
  http: ^1.1.0  # Necessario per SSL override
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Database - Desktop
  sqflite_common_ffi: ^2.3.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_virgo.png
    - assets/images/logo_virgo_extended.png