name: ai_assistant_mvp
description: AI Integration Platform for Business
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Navigation
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  go_router: ^13.2.0
  
  # Network & APIs (solo alcune per web)
  dio: ^5.4.0
  # googleapis: ^11.4.0      # Non funziona su web senza setup
  # google_sign_in: ^6.2.1   # Non funziona su web
  
  # Local Storage (disabilitato per web)
  # sqflite_common_ffi: ^2.3.0   # Non funziona su web
  # shared_preferences: ^2.2.2   # OK su web ma non necessario ora
  # hive: ^2.2.3                 # Non necessario ora
  # hive_flutter: ^1.1.0         # Non necessario ora
  
  # File System (disabilitato per web)
  # file_picker: ^6.1.1          # Funziona su web ma non necessario ora
  # path_provider: ^2.1.2        # Non funziona su web
  
  # Security (disabilitato per web)
  # flutter_secure_storage: ^9.0.0  # Non funziona su web
  
  # UI Platform-Specific (disabilitato per web)
  # macos_ui: ^2.0.2   # Non funziona su web
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.20.2
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/config/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700