name: ai_assistant_mvp
description: "AI Integration Platform for Business - MVP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  go_router: ^13.2.0
  
  # Network & APIs 
  dio: ^5.4.0
  
  # Local Storage (per ora solo quello che funziona)
  shared_preferences: ^2.2.2
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true